# example profiles
users:
  - id: u1
    name: Student Low Income
    monthly_income: 3200
    style: student
    notes: "high food, sporadic shopping"
  - id: u2
    name: Early Professional
    monthly_income: 5200
    style: professional
    notes: "subscriptions + eating out"
  - id: u3
    name: Family
    monthly_income: 8500
    style: family
    notes: "high fixed (rent), wants savings"
categories:
  - food
  - rent
  - shopping
  - transport
  - subscriptions
  - health